### ISSUE TITLE
make server port configurable

### ISSUE THREAD

**Issue by gAmUssA** [pozil/streamdeck-restream-plugin#1]
hello 
First, thank you for your work on this plugin! 

During the startup node server crashes with 

```
Starting WSS on port 5000
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1897:16)
    at listenInCluster (node:net:1945:12)
    at Server.listen (node:net:2037:7)
    at new WebSocketServer (/Users/vikgamov/projects/streamdeck/streamdeck-restream-server/node_modules/ws/lib/websocket-server.js:102:20)
    at file:///Users/vikgamov/projects/streamdeck/streamdeck-restream-server/src/server.js:8:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:518:28)
    at emitErrorNT (node:net:1924:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5000
}
```
Could you make node server port configurable. Under macosx port 5000 is used by system service `ContolCenter` and it can't be disabled. 

Thank you

**Comment by gAmUssA** [comment]
wrong repo https://github.com/pozil/streamdeck-restream-server/issues/2
